{% set name = "libsoup" %}
{% set version = "2.72.0" %}
{% set version_majmin = '.'.join(version.split('.', 2)[:2]) %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://download.gnome.org/sources/{{ name }}/{{ version_majmin }}/{{ name }}-{{ version }}.tar.xz
  sha256: 170c3f8446b0f65f8e4b93603349172b1085fb8917c181d10962f02bb85f5387

build:
  number: 2

requirements:
  build:
    - {{ compiler('c') }}
    - meson
    - ninja
    - pkg-config
    - gobject-introspection
  host:
    - glib
    - sqlite
    - libxml2
    - brotli
    - libpsl
    - glib-networking
    - zlib
  run:
    - sqlite
    - glib-networking
    - glib
    - libxml2
    - brotli
    - libpsl
    - zlib
    - gettext

test:
  requires:
    - {{ compiler('c') }}
    - pkg-config
  commands:
    - test -f ${PREFIX}/include/libsoup-2.4/libsoup/soup.h                   # [unix]
    - test -f ${PREFIX}/lib/libsoup-2.4.dylib                                # [osx]
    - test -f ${PREFIX}/lib/libsoup-2.4.so                                   # [linux]
    - test -f ${PREFIX}/lib/girepository-1.0/Soup-2.4.typelib                # [unix]
    - test -f ${PREFIX}/lib/pkgconfig/libsoup-2.4.pc                         # [unix]
    - if not exist %LIBRARY_LIB%\\pkgconfig\\libsoup-2.4.pc exit 1           # [win]
    - if not exist %LIBRARY_LIB%\\girepository-1.0\\Soup-2.4.typelib exit 1  # [win]
    - if not exist %LIBRARY_INC%\\libsoup-2.4\\libsoup\\soup.h exit 1        # [win]
    - if not exist %LIBRARY_BIN%\\soup-2.4-1.dll exit 1                      # [win]
    - if not exist %LIBRARY_LIB%\\soup-2.4.lib exit 1                        # [win]

about:
  home: https://gitlab.gnome.org/GNOME/libsoup
  license: LGPL-2.1-or-later
  license_family: LGPL
  license_file: COPYING
  summary: HTTP client/server library for GNOME

extra:
  recipe-maintainers:
    - tschoonj
