{% set version = "3.6.6" %}

package:
  name: libsoup
  version: {{ version }}

source:
  url: https://gitlab.gnome.org/GNOME/libsoup/-/archive/{{ version }}/libsoup-{{ version }}.tar.gz
  sha256: 828c357f6deca0646744ca2045870a8a215cd97a87357069b8fe94a786d8c316

build:
  number: 0
  run_exports:
    # Seems to have excellent forward compatibility in the 2.x series
    # https://abi-laboratory.pro/index.php?view=timeline&l=libsoup
    - {{ pin_subpackage('libsoup', max_pin='x') }}

requirements:
  build:
    - {{ stdlib('c') }}
    - {{ compiler('c') }}
    - meson
    - ninja
    - pkg-config
    - gobject-introspection
    # for native build prior to cross build
    - gettext     # [build_platform != target_platform]
    - glib        # [build_platform != target_platform]
    - sqlite      # [build_platform != target_platform]
    - libnghttp2  # [build_platform != target_platform]
    - brotli      # [build_platform != target_platform]
    - libpsl      # [build_platform != target_platform]
    - glib-networking  # [build_platform != target_platform]
    - libgirepository  # [build_platform != target_platform]
    - zlib        # [build_platform != target_platform]
  host:
    - glib
    - sqlite
    - brotli
    - libnghttp2
    - libpsl
    - glib-networking
    - libgirepository
    - zlib
    - libintl-devel   # [win]
  run:
    # Needs run export
    # https://github.com/conda-forge/glib-networking-feedstock/pull/28
    - glib-networking

test:
  requires:
    - {{ compiler('c') }}
    - pkg-config
    - pygobject
  commands:
    - test -f ${PREFIX}/include/libsoup-3.0/libsoup/soup.h                   # [unix]
    - test -f ${PREFIX}/lib/libsoup-3.0.dylib                                # [osx]
    - test -f ${PREFIX}/lib/libsoup-3.0.so                                   # [linux]
    - test -f ${PREFIX}/lib/girepository-1.0/Soup-3.0.typelib                # [unix]
    - test -f ${PREFIX}/lib/pkgconfig/libsoup-3.0.pc                         # [unix]
    - if not exist %LIBRARY_LIB%\\pkgconfig\\libsoup-3.0.pc exit 1           # [win]
    # Manually enable gi tests in run_tests.py before uncommenting this line
    # - if not exist %LIBRARY_LIB%\\girepository-1.0\\Soup-3.0.typelib exit 1  # [win]
    - if exist %LIBRARY_LIB%\\girepository-1.0\\Soup-3.0.typelib exit 1      # [win]
    - if not exist %LIBRARY_INC%\\libsoup-3.0\\libsoup\\soup.h exit 1        # [win]
    - if not exist %LIBRARY_BIN%\\soup-3.0-0.dll exit 1                      # [win]
    - if not exist %LIBRARY_LIB%\\soup-3.0.lib exit 1                        # [win]

about:
  home: https://gitlab.gnome.org/GNOME/libsoup
  license: LGPL-2.1-or-later
  license_family: LGPL
  license_file: COPYING
  summary: HTTP client/server library for GNOME

extra:
  recipe-maintainers:
    - tschoonj
